name: GraalVM Native Image Build

on: push

#on:
#  push:
#    tags:
#      - "v*.*.*"

jobs:
  build:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '21.0.0'
          java-version: '8'
          components: 'native-image'
          github-token: ${{ github.token }}

      - name: show info
        run: |
          java -version
          native-image --version
          mvn --version

      - name: maven build
        run: |
          mvn clean package -DskipTests
          tree .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            */target/*
            !*/target/*.jar